### ISSUE TITLE
Get rid of deprecated @material-ui/pickers usage

### ISSUE THREAD

**Issue by haakemon** [Altinn/app-frontend-react#146]
The [library ](https://github.com/mui-org/material-ui-pickers)has been deprecated for well over a year, and we have very limited usage (only used in DatePicker component), so hopefully upgrage should be relatively straightforward.

As part of this, we may need to upgrade to [material v5](Altinn/app-frontend-react#174), or find another alternative date picker.

**Comment by adamhaeger** [comment]
We had a discussion today regarding this and agree that it should prioritized asap as we will not be able to run react 19 with these mui versions.

We se a few alternative approaches:

1. Upgrade to mui5 and find a new datepicker.
2. Write our own grid, and datepicker. This way we can get rid of mui altogether.

The task should be to evaluate these options and decide the path forward.

@Edavda will also check with the Designsystem team what their plans are for a new datepicker so that we can hopefully collaborate.
