### ISSUE TITLE
Split up the Group component into different components

### ISSUE THREAD

**Issue by olemartinorg** [Altinn/app-frontend-react#1486]
### Description

After #1406, we've come a bit further on the [quest to split up the Group component](https://github.com/Altinn/app-frontend-react/issues/339#issuecomment-1494019302). With different types for each sub-component, it is obvious that we should do the rest of the job and separate these components altogether.

My suggestion:
- `RepeatingGroup` replaces a repeating `Group`
- `LikertGroup` replaces a repeating `Group` with edit-mode set to `likert`
- `Group` stays as-is, or is renamed to `Collection` or similar. If it is not renamed, we should make sure app developers are given ample warnings if they re-use old configuration.
- `Group` with `Panel` styling should be moved to the `Panel` component, using `children`, if possible
- Panels with group-reference should be separated into a distinct component (`RepeatingGroupReference`?)

### Additional Information

- #339

**Comment by Magnusrm** [comment]
Relevant slack discussion: https://altinndevops.slack.com/archives/C045EB3JA9X/p1701786089111159
For info: @lassopicasso @olemartinorg @Febakke @RonnyB71 

After fetching all altinn apps currently in production and tt02 using the fetch script i have found these uses of the `"Panel"` and "Panelgroup" components:

I am disregarding our own e2e test apps.

## Panel-group with repeating group reference

No one is using this

## Panel-group 

`"Group"` component with `"panel"` property set.

There are 27 instances of this configuration being used.
- Every instance has `"showIcon": false`. (Not using icon)
- 25 instances use the `"info"` color 
- 2 instances in the same app use the `"success"` color

The app using `"success"` is the signing app "KRT-1185 Forsikringsforetakets behandling av klientmidler"
It is used to group a button-group used to sign with the tekst reading in the lines of "I am confirming that the form is correct". 
<img width="1133" alt="Screenshot 2023-12-13 at 13 46 52" src="https://github.com/Altinn/app-frontend-react/assets/32294735/813dfc66-25de-4017-ad71-d914d597849c">

Alternatives after removing `"panel"` property:
1. with `"groupingIndicator"` set to panel (will allways be `"info"` color)
- sidenote: alert is being used instead of panel for the top message
<img width="1121" alt="Screenshot 2023-12-13 at 13 55 13" src="https://github.com/Altinn/app-frontend-react/assets/32294735/2eea6b7b-f93a-48e8-bc4c-6e68962cb3c5">

2. using `"showGroupingIndicator"` and changing the `"Paragraph"` component to `"Alert"`.
<img width="1113" alt="Screenshot 2023-12-13 at 13 53 13" src="https://github.com/Altinn/app-frontend-react/assets/32294735/6e91970b-31f4-4bd8-8a94-998b31b139a3">

3. using using `"showGroupingIndicator"` and changing the `"Paragraph"` component to `"Alert"` as info.
<img width="1111" alt="Screenshot 2023-12-13 at 13 52 51" src="https://github.com/Altinn/app-frontend-react/assets/32294735/697eb1a4-3f37-4934-a8c0-6c7e9138524f">

4. We could also not group the text and button group at all and just have the text as an info Alert say "By signing this form I am confirming ..."

Other examples of PanelGroup and an alternative solution:
<img width="1098" alt="Screenshot 2023-12-13 at 15 10 15" src="https://github.com/Altinn/app-frontend-react/assets/32294735/a508083d-717c-4c5e-9860-5fcaca10657e">
<img width="1060" alt="Screenshot 2023-12-13 at 15 12 29" src="https://github.com/Altinn/app-frontend-react/assets/32294735/f3adfcd9-44dd-4673-b0a5-418bdfa03fe2">

<img width="1098" alt="Screenshot 2023-12-13 at 15 01 46" src="https://github.com/Altinn/app-frontend-react/assets/32294735/2a93b267-40c7-4532-87ae-41c2258cd836">
<img width="1026" alt="Screenshot 2023-12-13 at 15 15 35" src="https://github.com/Altinn/app-frontend-react/assets/32294735/f40f12c5-b047-421b-b14a-3cf23733c48c">


## Panel

`"Panel"` component with title and body.

There are about 1000 instances of `"Panel"` being used in this way throughout our apps. Whereas `"Alert"` is used about 160 times.

Some before and after examples of using `"Alert`" instead of `"Panel"`:
<img width="1132" alt="Screenshot 2023-12-13 at 12 33 56" src="https://github.com/Altinn/app-frontend-react/assets/32294735/28716def-63be-4aa2-86c4-e780c159f707">
<img width="1140" alt="Screenshot 2023-12-13 at 12 35 03" src="https://github.com/Altinn/app-frontend-react/assets/32294735/30558afd-04a8-4bf5-b31e-b78d829425fe">

<img width="1101" alt="Screenshot 2023-12-13 at 13 18 48" src="https://github.com/Altinn/app-frontend-react/assets/32294735/c2315dde-96a5-49e7-8248-262740d65b72">
<img width="1118" alt="Screenshot 2023-12-13 at 13 19 05" src="https://github.com/Altinn/app-frontend-react/assets/32294735/09b68a99-ed6b-400c-aa49-e60da611e0c0">

<img width="1124" alt="Screenshot 2023-12-13 at 12 24 44" src="https://github.com/Altinn/app-frontend-react/assets/32294735/16b6d5ba-04ce-4c35-a62d-45c260cabf19">
<img width="1116" alt="Screenshot 2023-12-13 at 12 23 54" src="https://github.com/Altinn/app-frontend-react/assets/32294735/af9c2881-5964-4b67-9aec-c3d314248e99">

<img width="1111" alt="Screenshot 2023-12-13 at 13 14 06" src="https://github.com/Altinn/app-frontend-react/assets/32294735/6b771f45-970c-46fe-9613-d6240978341e">
<img width="1117" alt="Screenshot 2023-12-13 at 13 15 19" src="https://github.com/Altinn/app-frontend-react/assets/32294735/4c897de4-4ae3-4de5-9734-c53241f1b472">

<img width="1141" alt="Screenshot 2023-12-13 at 12 31 29" src="https://github.com/Altinn/app-frontend-react/assets/32294735/af6aa73c-7716-48cc-82e8-a9bb1a335181">
<img width="1140" alt="Screenshot 2023-12-13 at 12 31 46" src="https://github.com/Altinn/app-frontend-react/assets/32294735/02bba9a0-7efc-45f3-a687-e86b8914e8b2">

<img width="1016" alt="Screenshot 2023-12-13 at 12 25 54" src="https://github.com/Altinn/app-frontend-react/assets/32294735/d46049b7-a5ec-480f-a532-accb8b09a51b">
<img width="983" alt="Screenshot 2023-12-13 at 12 27 24" src="https://github.com/Altinn/app-frontend-react/assets/32294735/a7171383-8d70-4ca4-82c0-3dcdedc13151">

<img width="1122" alt="Screenshot 2023-12-13 at 12 30 21" src="https://github.com/Altinn/app-frontend-react/assets/32294735/95f90a83-bbbb-49a4-ae11-84c5e5b18078">
<img width="1120" alt="Screenshot 2023-12-13 at 12 30 51" src="https://github.com/Altinn/app-frontend-react/assets/32294735/ffe1dd34-3ede-423a-b3b0-3d67f7cf094e">

<img width="1160" alt="Screenshot 2023-12-13 at 15 28 45" src="https://github.com/Altinn/app-frontend-react/assets/32294735/b4deb7fb-1ab2-4704-b599-29d14798deb0">
<img width="1085" alt="Screenshot 2023-12-13 at 15 28 34" src="https://github.com/Altinn/app-frontend-react/assets/32294735/8d526ca3-7523-4509-9b4c-eda7c65e1140">
