### ISSUE TITLE
Repeating groups: Sticky header og begrensning på antal rader som vises samtidig

### ISSUE THREAD

**Issue by rvessb** [Altinn/app-frontend-react#1492]
### Description

Ved mange rader i repeterede gruppe vil kolonneoverskriftene forsvinne ut av bildet ettersom man blar seg nedover på siden.
![image](https://github.com/Altinn/app-frontend-react/assets/43333852/2b02da42-0500-46e4-aa1a-47589262307c)
Nedenfor er samme tabell med kun 3 rader
![image](https://github.com/Altinn/app-frontend-react/assets/43333852/6e908233-9f50-441b-9dd9-d27a3bf7282c)

Vi ønsker oss en mulighet til å fryse både overskriftsrad og summeringsrad. Antall rader som til enhver tid skal være synlig mellom topp og bunn må kunne styres vha settings. 

Et alternativ kan være at kun overskriftsrad "henger igjen" på siden (Sticky Header).

Fra slack: https://altinn.slack.com/archives/C02EVE4RU82/p1695290285907469

```[tasklist]
### Design Tasks
- [ ] https://github.com/Altinn/app-frontend-react/issues/1760
```

**Comment by olemartinorg** [comment]
Relevant:
- #581 
- #1210 (denne beskriver sticky kolonner, men ikke sticky headere/rader)

**Comment by Magnusrm** [comment]
I think the issue to be solved here is the underlying need of a user to more easily navigate large tables and be able to not lose the context that the header provides. 
Therefore, I think we should briefly explore some other possible solutions to this issue before settling on how to solve the issue.

Some solutions with some pros and cons I can think of:

Sticky header:
- (+) Context of the header will always be easily available
- (-) Still requires a lot of scrolling to view contents
- (-) Still requires you to scroll through the whole table to get to the next component

Scrollable table-body with fixed (or maybe user-controlled 🤔 ) height:
- (+) Context of the header will always be easily available
- (+) Next component in form is a short scroll away
- (-) Still requires a lot of scrolling to view contents

Pagination (dividing the table contents into pages 1,2,3…):
- (+) Context of the header will always be easily available
- (+) Next component in form is a short scroll away
- (+)? No scrolling required
- (-) Less seamless navigation of contents
- (-) Related information might live in separate pages and require clicking back and forth

There might be some other pros and cons that I’ve missed for these solutions, other thoughts about pros and cons and other ideas are welcome!

Something we must also consider is what solution is more accessible with tools like screen readers. 

The pagination solution could be beneficial in the way that a screen reader user could quickly navigate to the middle of the table contents via the middle “page”. 

The sticky header solution and the scrollable table solution i would guess probably works about the same as today for screen reader users. The user might need to tab through the whole table to progress the form, since the repeating-group can contain interactive elements, unless we add a “skip-link” for screen readers (which we probably should do regardless).

Any thoughts and insigths about what might be a good UX @olavflar @Febakke ?

**Comment by olemartinorg** [comment]
Loving the writeup, @Magnusrm! :raised_hands: Beware that pagination is a separate issue in #581 as well, so we might want to offer multiples (or all of) these features, and making them configurable. I would think there's not a one-size-fits-all for all use-cases here, and it might depend a lot on the importance of the data in the repeating group compared with the rest of the data in the current form page.

**Comment by Magnusrm** [comment]
@olemartinorg Great point about the possible need of making several of the features configurable! 🙌 . Maybe we can leave pagination for later then, and start with a configurable "scrollable" solution then. 

I am leaning towards the second option listed then, which in my mind:
-  enables vertical scrolling for the table body
-  limits the height of the table in some way
-  keeps the header unaffected

**Comment by olemartinorg** [comment]
Yup, a setting for how many rows to maximally display at once (before breaking and introducing a scrollbar) can work, but I guess the use-case @rvessb is working on should be the one to decide what we implement first here.
