### ISSUE TITLE
Repeating group: In specific cases there are a delete button that do not work

### ISSUE THREAD

**Issue by Febakke** [Altinn/app-frontend-react#1668]
### Description of the bug

In cases where repeating groups are set up so that the user has to have atleast one group. There is a delete button present that does nothing. We should hide this button if the user cant use it. 

**Example:** In this case one group must be present. This is the view the user are shown when entering the page. You can click the delete button but nothing happens. It would be best to hide this button. 

![Skjermbilde 2023-11-29 kl  10 55 17](https://github.com/Altinn/app-frontend-react/assets/33222679/0fdb875f-146a-4d58-872c-ab0544b89ea1)

### Steps To Reproduce

1. Find an app with the scenario explained above.
2. Try to click the delete button

**Comment by olemartinorg** [comment]
I'm assuming this refers to the `openByDefault` functionality in repeating groups. This issue has now been fixed in v4, and 'open by default' is a lot less eager to create new rows, and in fact only does it _by default the first time the user sees that repeating group_, or when the user navigates away and returns to the repeating group. So the delete button now has an effect, but only for a while until you possibly return to the group again. If you don't return to the group, and it's been set up to allow for 0 rows to be submitted, it's also possible to submit the form without one.
