### ISSUE TITLE
IAppOptionsProvider does not provide options if "mapping" field is never set

### ISSUE THREAD

**Issue by violaguttorm** [Altinn/app-frontend-react#1685]
### Description of the bug

I have a field that gets values through an implementation of an `IAppOptionsProvider` (calling this field the DYNAMIC FIELD), and these values are dynamically determined based on another field in the same form (calling this field the DEPENDENCY FIELD). However, there are ways to fill out this form without ever filling out the DEPENDENCY FIELD, and when you do that the DYNAMIC FIELD will just be stuck with a loading icon. The code in the `IAppOptionsProvider` can handle this value not being set, but it is never run during a regular filling out of the form if you do not fill out the DEPENDENCY FIELD. 

What I want is for the `IAppOptionsProvider` to run when the form is first loaded in, even though the DYNAMIC FIELD is hidden at this point. I'm almost sure this has worked before, but I couldn't say when.

### Steps To Reproduce

1. Create a List with four fields in the data model: "isDependency" (bool), "dependencyPercentage" (string), "isDynamic" (bool) and "dynamicPercentage" (string). Make all RadioButtons inside a Repeating Group. (Repeating Group POSSIBLY not needed)
2. Make "dependencyPercentage" and "dynamicPercentage" hidden if "isDependency" and "isDynamic" (respectively) are not "true". 
3. Make "dynamicPercentage" get its options from an implementation of `IAppOptionsProvider` that has "dependencyPercentage" as a variable (through "mapping" in the layout-file). 
4. Select "No" on "isDependency", select "Yes" on "isDynamic". 
5. Observe that the option for "dynamicPercentage" is just stuck on loading, since "dependencyPercentage" was never called.

**Comment by bjosttveit** [comment]
@violaguttorm do you have an app with this setup so I can try to reproduce this?

**Comment by violaguttorm** [comment]
@bjosttveit It is this app. You will probably have to test it in TT02 at least to begin with, as it's somewhat problematic to get it up and running locally outside our environment. 

https://altinn.studio/repos/brg/rrh-innrapportering 

1. You can use an organization of type AS to start the form.  
2. Select "Har rettighetshavere"
3. Select "Har fødselsnummer/d-nummer" (ignore filling out personal information)
4. Set "Har posisjon eierskap?" to "Nei"
5. Set "Har posisjon kontroll over stemmerettigheter?" to "Ja"
6. Observe it loading for eternity.
7. Observe that on a refresh it shows up as it should. 
8. Observe that if you set "Har posisjon eierskap?" to "Ja" first and actually choose an alternative on "Hvor stor er andelen?", _then_ set "Har posisjon eierskap?" to "Nei", it will also show up as it should.

**Comment by bjosttveit** [comment]
I tried running it locally on the latest frontend v4 and nuget v8 to see if it was fixed, but I got some 500 responses from the custom options, due to NullReferenceException when testing the mappong parameters.

Sidenote: in v4, mapping should return an empty string if the value is not set in the form, instead of "undefined". This will come in RC4 as it was merge just after RC3 released.

I suggest you should try to update the app to v4/v8, and make the necessary changes for that and see if it works. Most fetching logic has been updated in v4, so it could be fixed there. But note that in RC3, a mapping that has an empty value in the form will not have a key in the dictionary. But in your case that should be fine, as you check if the key exists or not. The NullReferenceException I got seems to stem from the `.Equals()` check after this for some reason.

**Comment by ivarne** [comment]
@violaguttorm Anything more that should be done on our side here?

It looks to me like @bjosttveit fixed a front end issue, but a NullPointerExeption remains in your IAppOptionsProvider code. Anything more we should look at?
