### ISSUE TITLE
Attachments disappear from state in repeating groups

### ISSUE THREAD

**Issue by MagnusMolaugFinans** [Altinn/app-frontend-react#1943]
### Description of the bug

If you upload an attachment to a FileUploadWithTag component (the same probably happens with normal FileUpload components) and then refresh the page, the attachment will disappear from the list. This causes the required validation to think that there is no file added despite the file existing in blob. If you then add another file then you'll see both the files for the same upload component on the receipt page. 

### Steps To Reproduce

1. Have a repeating group with a FileUploadWithTag component
2. Add an attachment, select a tag and save the attachment
3. Refresh the page
4. the file will now be missing

### Additional Information

There is no limit to the amount of files you can upload by doing this

**Comment by olemartinorg** [comment]
@MagnusMolaugFinans Which app is this? We have automatic tests for this functionality which haven't failed recently, so I suspect there is something specifically in the app that went wrong when you got this problem.

Also, have you followed the [setup guide for attachments in repeating groups](https://docs.altinn.studio/app/development/ux/fields/grouping/repeating/attachments/)? You have to make sure to set up a data model binding for the file upload component when used in repeating groups (same goes for `FileUploadWithTag`), otherwise you'll get pretty much this behavior.

**Comment by olemartinorg** [comment]
Debugged this and communicated via Slack. Not an issue in app-frontend, but a problem with the data model setup in the app. Closing as not planned.
