### ISSUE TITLE
Decimalscale fører til krasj

### ISSUE THREAD

**Issue by palmanshaus** [Altinn/app-frontend-react#2066]
### Description of the bug

Om man har et decimal-felt man legger til decimalscale på for å ikke vise uendelig antall sifre så prøver systemet omgjøre og krasjer, da det ikke klarer få samme verdi i double og decimal (?)

### Steps To Reproduce

Sett opp kalkulering av et felt basert på 2 felter som deles på hverandre og sett decimalscale på visning av gitt resultat

### Additional Information

Mer info her:
https://altinn.slack.com/archives/C02EJ9HKQA3/p1714397755611139?thread_ts=1714397755.611139&cid=C02EJ9HKQA3

**Comment by martinothamar** [comment]
We just had a meeting regarding this, came to some conclusions

* Investigate what it would take to serialize numbers as strings instead
* Long term we need to make improvements on the datamodel generation
  * Encourage constrained numeric types that map to 32bit ints and 64bit floats at most

@altinnadmin @mirkoSekulic @framitdavid @ivarne

**Comment by martinothamar** [comment]
Conclusion: cost of doing string serialization for large types deemed too high to support this. In the future we will constrain datamodel generation so that only numeric types that are fully representable in both .NET and JS are used in datamodels (32 bit integers and 64 bit floating point). 

@olemartinorg did you push a fix for the unnecessary patch request for the calculcated field that you found? Should we close?

**Comment by olemartinorg** [comment]
Jeg flyttet denne over til sprint 46, da den ble liggende igjen i review i sprint 44. Jeg har fortsatt en feilretting her i en branch (app-frontend-react) som jeg vil ha ut.
