### ISSUE TITLE
Support pregenerated subforms where one or more rows are ready for editing

### ISSUE THREAD

**Issue by HauklandJ** [Altinn/app-frontend-react#2202]
BR (Brønnøysundregistrene) needs the possibility to have a number of pre-added subform rows in the subform table. These should be possible to configure on the back end. 

Requirements:

- Pre-added sub forms should be shown as a row in the sub form table.
- The sub form should require editing (?). This will solve itself if there are required, non-prefilled fields in the sub form
- It should be possible to disable the "Add new sub form"-button (this could be done with the maxCount-prop in applicationMetadata.json - given that the add-button reuses the logic from repeating groups)

**Comment by danielskovli** [comment]
I think we're already supporting this by default from our existing implementation. Since we're using the DataController to create DataElements, and this controller supports the insertion of data alongside the request to create the element itself.

Atleast that's my understanding of the process. Will investigate.
