### ISSUE TITLE
Handle dynamic data in Percy to avoid false negatives

### ISSUE THREAD

**Issue by cammiida** [Altinn/app-frontend-react#2566]
There is some dynamic data in our components, like the help text for the datepicker which is based on `new Date()`. This will change the screenshot in Percy for every new day and result in changes to review, even though this is totally valid changes.

There is a way to fix this by using dynamic data described [here](https://www.browserstack.com/docs/percy/stabilize-screenshots/dynamic-data).

**Comment by bjosttveit** [comment]
We typically add the class `.no-visual-testing` to elements which change dynamically (like instance-ids etc.), we have some [percy specific css](https://www.browserstack.com/docs/percy/advanced-snapshots/percy-css#snapshot-options--sdk-options) that will black out elements with this class so that we don't get any visual changes
