### ISSUE TITLE
Forrige Neste knapp blir ikke klikkbare og gråe i brøkdel av et sekund når man velger noe

### ISSUE THREAD

**Issue by DanRJ** [Altinn/app-frontend-react#2665]
### Description of the bug

I appen vår oed-declaration i tt02 vil navigasjonsknappene blir gråe og ikke klikkbare når man gjør en endring via en skjemakomponent f.eks radioknapp.

Jeg downgradet fra nyeste i v4 til 4.8.2 og det løste dette.

### Steps To Reproduce

1. Gå til tt02
2. Logg inn med 20911749646
3. Velg meldingen fra Digitalt Dødsbo
4. Bla ned til "4. Velg skifteform for dødsboet" og klikk på den
5. Velg fanen "Velg skifteform"
6. Trykk på knappen "Endre skifteform"
7. Finn noen radioknapper
8. Trykk litt på de, se at navigasjonsknappene blir gråe og ikke klikkbare

**Comment by adamhaeger** [comment]
Dette er 'by design'. Tidligere var det mulig å klikke seg videre før endringene var lagret, noe som gjorde at dersom man hadde treg internett forbindelse så hopet lagringrene seg opp noe som førte til inkonsistent tilstand senere.

Jeg lukker denne for nå men har sagt fra til designeren vår at de tar en vurdering på om dette burde løses på en annen måte i fremtiden.
