### ISSUE TITLE
Likert with a divider

### ISSUE THREAD

**Issue by tina-ahm** [Altinn/app-frontend-react#2671]
### Description

We would like for the option to have a dividing (vertical) line in the answers section of the Likert component.

Here are some examples:
![Image](https://github.com/user-attachments/assets/645fbcc5-630c-4c2d-bbed-20d7cb1902d0)
![Image](https://github.com/user-attachments/assets/6e546848-2fb0-4ca0-bcaf-50682cc1fcae)

**Comment by Edavda** [comment]
Could you add some more context to the reason for adding this divider? What needs are we looking to cover here? @tina-ahm

**Comment by Edavda** [comment]
Feedback from SSB states that the divider is required in order to separate some columns from the rest of the scale. 
In SSB's case, they need to include two alternative answers that are somewhat detached from the incremental scale. The thought is that a vertical divider would be a good visual aid to distinguish these columns. 

I would suggest to test a variant where the background color in the header row is different for the answers they want to separate from the rest. Maybe that would be enough to indicate that these belong to a different group. 

![Image](https://github.com/user-attachments/assets/bbd8d10d-ad3c-4934-90d5-17a2d9ecb3bb)



If a color change is not sufficient, then a vertical divider can be used in addition or as the only way of separation. 

![Image](https://github.com/user-attachments/assets/652a840a-0e36-4cc4-b6ed-e7e8437fc658)


Both designs can be [found here](https://www.figma.com/design/Pvti3aRcOwH0k5Z7DrLznk/Arbeidsomr%C3%A5de%3A-Altinn-Studio-APPS?node-id=8375-28963&t=QsvjoeBmzXkSAd2t-4)
