### ISSUE TITLE
Layout error when navigating between pages

### ISSUE THREAD

**Issue by akselhmadslien** [Altinn/app-frontend-react#481]
### Description of the bug

the field 2-3prefix from summary.json appears on information-page after visiting the summary-page. Disappears again after refresh

### Steps To Reproduce

1. run the app: 
[krt-1036a-1-master.zip](https://github.com/Altinn/app-frontend-react/files/9614017/krt-1036a-1-master.zip)
2. log in as sophie salt and select any business
3. visit summary page by pressing next-button on bottom of page
4. use back button on page to revisit the information-page
5. observe the top field 
![image](https://user-images.githubusercontent.com/113341457/191440936-121cd24c-6f0c-4d8e-9000-1a4424898009.png)
Top field 2.1 Landkode should not be there
7. refresh page to make the field disappear

### Additional Information

Tested with different javascript versions. 3.47.0 is the first version without the problem: https://github.com/Altinn/app-frontend-react/releases/tag/v3.47.0

**Comment by akselhmadslien** [comment]
Found a duplicate in an id in two summary-components: fixed now, so resolved issue, but still strange behaviour

**Comment by olemartinorg** [comment]
> Tested with different javascript versions. 3.47.0 is the first version without the problem

Did I understand correctly that the problem has been fixed, @akselhmadslien? Btw, this might have happened because dashes followed by short numbers in the component `id` might interfere with internal state we add to the components to differentiate them when used in repeating groups. Try making sure your component `id` does not follow a pattern of `something-1` or similar. Try rewriting it to `something1` to see if that fixes problems.

**Comment by akselhmadslien** [comment]
The problem has been fixed, yes. Thank you
