### ISSUE TITLE
Technical analysis table app frontend

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/app-frontend-react#543]
## Description
Based on Altinn/app-frontend-react#107  analyse how table should be implemented

## Considerations

- [ ] Are there any components that can be reused 
- [ ] How to structure work? Interations? First versio
- [ ] Create implementation task?
- [ ] View only mode in first iteration

## Specification tasks

- [ ] Development tasks are defined

## Definition of done

- [ ] Documentation (docs.altinn.studio) is updated (if relevant)
  - [ ] Technical documentation
  - [ ] User documentation
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by olemartinorg** [comment]
We had a refinement meeting about this today. First of all, I'm pulling in some of the other relevant issues/projects I could find regarding this:

- Altinn/app-frontend-react/issues/107
- Altinn/altinn-studio/issues/378
- Project view: https://github.com/orgs/Altinn/projects/3/views/15
- Slack thread about proposed solutions (in Norwegian): https://altinndevops.slack.com/archives/C045EB3JA9X/p1665582256646189

The underlying Table component has been designed, and is currently being implemented in the design system. However, the technical solution for how to implement this in app-frontend remained somewhat undefined.

The meeting concluded that we want to re-use the Table from the design system in three different layout components in app-frontend, each having their own properties. Their uses and limitations are well-defined, but we identified that naming these might lead to confusion (since visually they're all tables):

1. The existing **repeating groups** component - which could just as well be named the 'table' component. This will continue to bear most of the complexity in app-frontend. The data model includes repeating elements (rows) which can be displayed in varying ways, from a compact table (with editing/input controls in each cell), to individual cards/"group" per row, potentially with more complex components inside, like nested repeating groups. We should implement an option to hide the edit button for a row, and selectively use input components inside cells directly in the table instead of the read-only table overview we have today.
2. **Grid**, aka static table, aka 'rutenett'. This new layout component will have a fixed number of rows and columns, and each cell needs to have its content specified. There is no relation to repeating elements in the data model for this component, as it's visually just a tabular structure to contain individual components. It's still somewhat unclear how well this will work with screen readers and accessibility, and perhaps many of these needs will be solvable in repeating groups regardless. For those reasons, this will most likely be the last component to be implemented/prioritized.
3. **List**. This new layout component is most similar to a dropdown, radio group or checkbox group. It is meant to display a table with a configurable amount of columns with cells containing richer data than what can already be shown using existing (dynamic) options/code lists. We'll need API endpoints for fetching data (including pagination options like which page we're on, start/stop indexes, along with which column to sort by and the sort direction). By passing [extra options as query parameters](https://docs.altinn.studio/app/development/data/options/#pass-query-parameters-when-fetching-options) when fetching these dynamic options (aka rows) it is possible to implement search/filtering.

**Comment by olemartinorg** [comment]
New issues have been created for specific implementations. Considering this issue to be done.
