### ISSUE TITLE
Exception when hiding a repeatable group containing a custom component.

### ISSUE THREAD

**Issue by JohanGuntherKrogevoll** [Altinn/app-frontend-react#596]
### Description of the bug

`Uncaught TypeError: Cannot delete property '__reactFiber$rnxumg1d0p' of [object Object]` is thrown when trying to hide a group containing a custom component. 

![Kapture 2022-11-01 at 10 38 44](https://user-images.githubusercontent.com/66003225/199204966-6a20d031-13d1-4e70-9773-6fde4af9076f.gif)

### Steps To Reproduce

1. Clone [this](https://altinn.studio/repos/dsb/uhell-transport-av-farlig-gods/pulls/1) repo and checkout the "custom_web_component" branch.
2. Start the app and navigate to "Varetype/produkt involvert"-page
3. Add a product to the repeatable group.

### Additional Information

[This issue](https://github.com/Altinn/app-frontend-react/issues/595)  may be related.
[Relevant slack conversation](https://altinn.slack.com/archives/C02EJ9HKQA3/p1666964899209489)

**Comment by olemartinorg** [comment]
@JohanGuntherKrogevoll This should be fixed in the latest release. Could you test it out and let me know if the fix works? :smiley:

**Comment by olemartinorg** [comment]
@JohanGuntherKrogevoll Sadly, I struggle to find a suitable workaround for this problem. My analysis below:

Your custom component looks like its using [react-to-webcomponent](https://github.com/bitovi/react-to-webcomponent), and thus wraps a React component. As I mentioned on Slack, it seems that when we remove a component from a repeating group (when deleting it), some custom state React puts directly on the component is attempted to be deleted, but that deletion causes the TypeError you see above. To be specific, React Fiber adds a property to your web component element to remind itself of the current DOM state, but that cannot be deleted for some reason. I see ample calls to [Obect.freeze()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze) in your code, so I suspect it's either something your copy of React (or react-to-webcomponent) does.

Right now, Custom components sadly have fairly non-existent documentation, and I struggle to find good (and simple) examples of how to implement one myself. I added one of our [demo components](https://altinn.studio/repos/ttd/custom-component-demo) to a repeating group, and that seemed to work fine - but I can't find a good source or example of how we suggest to implement a custom web component using plain web components (instead of something like react-to-webcomponent).

The way I see it, we have these choices:

1. We start supporting external React components, not just web-components. Unknown amount of effort involved, and a new feature I'm not sure we are able to prioritize at the moment.
2. You could rewrite your component to a plain web-component.
3. If at all possible, you could configure your copy of React (or react-to-webcomponent) not to freeze the object (or otherwise set our properties to read-only).

**Comment by olemartinorg** [comment]
As discussed on Slack, this might become an external contribution in the form of a autocomplete select-field. Closing this issue as won't-fix/can't-fix.
