### ISSUE TITLE
Summary component: Visning av repeterende gruppe med Header viser samme tekst på alle rader

### ISSUE THREAD

**Issue by StianVestli** [Altinn/app-frontend-react#883]
### Description of the bug

Har en repeterende gruppe:
![image](https://user-images.githubusercontent.com/91887041/216015827-257954bf-a045-45c2-9262-c808e27632c9.png)
som er lagt til på summering:
![image](https://user-images.githubusercontent.com/91887041/216015886-49d3f7e6-b41d-426c-a136-9957e8f104e7.png)
 som man ser vises tittel feltet i summering den samme verdien på alle radene.
Denne repgrupper har et header objekt i repgruppa, Underenhet nr 1, 2, 3 og 4 denne er får teksten via en språk ID som har har variabel fra datamodellen som setter teksten pr rad.

### Steps To Reproduce

Repo med problem: https://altinn.studio/repos/stian.vestli/ra0244-01.git
commit: 97929ff376e7253943e096dd5639c87958990d2f

**Comment by bjosttveit** [comment]
The issue here seems to be that when the `SummaryComponent` displays `GenericComponent`, it passes `formComponentLegacy` which causes the row-information contained in the layout node to be lost. The fix is to simply give it the resolved node instead, but I am not sure how to make typescript happy about that. Could you look into it maybe @olemartinorg ? I looked at the `chore/expr-type-cleanup` branch since many types are changed there.

![Image](https://user-images.githubusercontent.com/47412359/220658335-388c2580-47bc-4b98-9ee3-aecd7ada020d.png)



![Image](https://user-images.githubusercontent.com/47412359/220658839-e068bb62-0ccd-48be-a2b1-9bb553d93998.png)

**Comment by StianVestli** [comment]
Teste nå og det ser bra ut.
