### ISSUE TITLE
Upgrading redux to 4.2.0 breaks build

### ISSUE THREAD

**Issue by tjololo** [Altinn/app-frontend-react#92]
## Description
Upgrading redux to 4.2.0 breaks the build of altinn-app-frontend

## To Reproduce
1. Go to '/src' in the repository 
2. Run 'yarn up redux@^4.2.0' to upgrade redux to 4.2.0
3. Go to `/src/altinn-app-frontend` in the repository
4. Run build `yarn build`
5. See build error

## Expected behavior
altinn-app-frontend builds with redux 4.2.0

**Comment by ivarne** [comment]
https://github.com/reduxjs/redux/releases/tag/v4.2.0

Seems to be a message from the authors that there are now better ways to initiate a store than `createStore`, so they marked it deprecated (with no plan of actual removal), so that users actually gets the message. Just change to `legacy_createStore` to remove the error.

**Comment by lorang92** [comment]
Solved in https://github.com/Altinn/app-frontend-react/pull/472.
