### ISSUE TITLE
Validation messages for attachment uploaders

### ISSUE THREAD

**Issue by lassopicasso** [Altinn/app-frontend-react#954]
### Description

Seems like our data structures for storing validation messages does not allow for metadata such as "which one of multiple attachments is this error for".
 
Example: dynamic components such as attachment upload with tags. 
When user uploads a file, a sub-component is added. The sub-component lets the user choose which tag the file is for and then save. If user doesn't choose a tag and just saves, the input is not validated and an error message should display in this field. Instead the message displays in the main-component. Current solution for this has been to include ID and a "Ascii separator" in the error message, so that the correct sub-component can be identified. From the validation.ts:
```
   if (missingTagAttachments?.length > 0) {
          missingTagAttachments.forEach((missingId) => {
            validations[node.item.id][fieldKey]?.errors?.push(
              `${
                missingId +
                AsciiUnitSeparator +
                getLanguageFromKey('form_filler.file_uploader_validation_error_no_chosen_tag', language)
              } ${(node.item.textResourceBindings?.tagTitle || '').toLowerCase()}.`,
            );
          });
        }
```
Later on a tracking error from this solution was uncovered, where the ID and Ascii separator being displayed in the error report . The work around solution for this can be found here: [Error message - remove long ID, duplication fix #942](https://github.com/Altinn/app-frontend-react/pull/942)

The solution with ID and Ascii separator included in the message shouldn't be the final solution, and instead we should enable the data structure to allow for metadata that identifies "which one of multiple attachments is this for".

**Comment by olemartinorg** [comment]
Solved in v4, @bjosttveit?

**Comment by bjosttveit** [comment]
Yes, the attachment id is now stored as metadata in the validation object and no longer pollutes the validation message. So this issue should be resolved.

Some lingering thoughts on this:
The validation is still internally tied to the file upload component, and not the attachment directly. This is because whether or not an attachment should have a tag is defined on the FileUpload component, and not the attachment data type itself (in applicationmetadata). This is a consequence of how we designed our configuration, which also means that this validation only exists in app-frontend and it will not work out-of-the-box in the backend. It should be possible to implement a custom task-validation in the backend to verify that tags are set, but task-validations cannot be tied to fields in the datamodel, much less components or attachments. So this would not be great for the end-user or the app-developer.

Possible solution:
Whether or not an attachment is required to have a tag could be defined in the dataType in applicationmetadata. The frontend could then have its own validation store for attachment validations that the different file-uploaders look to for validations of specific uploaded attachments (similar to how components look for validations for datamodel fields they are bound to). The backend could then have an out-of-the-box validator for the same thing.

AFAIK no one has requested this feature, so just leaving it there for now.
