### ISSUE TITLE
Validation: New design for error messages connected to user inputs

### ISSUE THREAD

**Issue by mrosvik** [Altinn/app-frontend-react#99]
## Description
_As a user I want to see that my input in a table contains an error when I leave the field, so that I can correct it._

The new design is made to work better with inputfields inside tables. Since we want to keep the validation-messages consistent and standarized, we should change the look for the whole solutions, not only for tables. 

Tables: [Issue 7750](Altinn/app-frontend-react#107)

## Design: 
https://www.figma.com/file/Pvti3aRcOwH0k5Z7DrLznk/Arbeidsomr%C3%A5de%3A-Altinn-Studio-APPS?node-id=2545%3A50628

<img width="2003" alt="image" src="https://user-images.githubusercontent.com/1464915/158800773-5e6aefac-0318-421d-a995-b45450bd346a.png">

<img width="1655" alt="image" src="https://user-images.githubusercontent.com/1464915/158800086-19bcc94f-e9a0-4790-9dbc-f4dd1f5caa4d.png">

## Development tasks
- [ ] Remove box around message, make text red.
- [ ] Add ! exclamation mark into the cell that has error.

## Definition of done

- [ ] Documentation (docs.altinn.studio) is updated (if relevant)
  - [ ] Technical documentation
  - [ ] User documentation
- [ ] QA
- [ ] Manual test is complete (if relevant)
- [ ] Automated test is implemented (if relevant)
- [ ] All tasks in this userstory are closed (i.e. remaining tasks are moved to other user stories or marked obsolete)

**Comment by olemartinorg** [comment]
Since this is almost done and will soon be tested, I'll add that I discussed this issue with @xmrsa today. They have noted an issue with long validation error messages belonging to short input fields. A prime example is the app in [#8369](/Altinn/altinn-studio/issues/8369) and [#8254](/Altinn/altinn-studio/issues/8254), where a fairly short input field can get a very long error message:

![20220817_16h16m56s_grim](https://user-images.githubusercontent.com/700139/185157495-835f70bd-c460-4e16-a1f5-1c2aaca292a2.png)

If this change does not better that situation, we should open a new issue for what to do with long error messages when there's room for them. In the [mentioned app](https://altinn.studio/repos/xmrsa/ra0678-01), the field has a grid (because it doesn't look good having a full-width field when your just supposed to type in a few digits) - but there is lots of room for the error message.

**Comment by rvessb** [comment]
Så langt vi kan se blir ikke radioknapper og sjekkbokser merket med rødt, på samme måte som rene input-felter. Da forsvinner feilmeldingsteksten når denne ikke lenger har den røde bakgrunnen som ble brukt tidligere.

**Comment by olemartinorg** [comment]
Hmm, ja, det er et godt poeng. Jeg ble nysgjerrig på hvordan det ser ut nå, og fikk dette:

![20220909_13h33m41s_grim](https://user-images.githubusercontent.com/700139/189341189-ef544b00-3024-4a0e-8cdc-cd5d4cb0f4d2.png)

Jeg tar det opp og finner ut hvordan vi skal gjøre det med veien videre, men jeg regner med det må på plass et nytt issue om vi ikke har noen allerede - det drunker i alle fall fort her i kommentarfeltet på en lukket sak. Oppdaterer her når jeg finner ut.

**Comment by olemartinorg** [comment]
@rvessb @xmrsa @benteSSB Det ble uke 39 istedenfor - men nå har jeg og @mrosvik diskutert denne saken. Vi holder for tiden på med å lage nye sjekkbokser (og radioknapper kommer vel også som en naturlig del etterpå) i designsystemet. Det åpenbare er helt klart å gjøre sjekkboksen/radioknappen rød når man ikke har krysset av noe, og i eksempelet over hadde det løst det meste.

Vi har også et annet scenario - når du f.eks. har 4 sjekkbokser og det bare er naturlig å krysse av i 1-2 av dem er det unaturlig at alle blir markert med rødt (det ville jo kanskje indikert at det er *feil* at du ikke har krysset av i *alle*), så vi prøver å se om vi finner et alternativ for steder hvor man har flere sjekkbokser. Mulig vi bare går for at alle sjekkboksene blir røde her også, da andre alternativer (f.eks. en rød vertikal strek på siden av sjekkboksene) innfører et nytt konsept brukerne ikke er kjent med fra andre steder i Altinn.

Uansett, vi anser denne saken som løst - så tar vi gjenstående utfordringer med oss videre under [oppgaven for sjekkbokser i designsystemet](https://github.com/Altinn/altinn-design-system/issues/86) og deretter implementasjonen av disse i frontend.
